/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as GearsRouteImport } from './routes/gears'
import { Route as DroneRouteImport } from './routes/drone'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SquadsIndexRouteImport } from './routes/squads/index'
import { Route as SquadsSquadIdRouteImport } from './routes/squads/$squadId'

const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const GearsRoute = GearsRouteImport.update({
  id: '/gears',
  path: '/gears',
  getParentRoute: () => rootRouteImport,
} as any)
const DroneRoute = DroneRouteImport.update({
  id: '/drone',
  path: '/drone',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsIndexRoute = SquadsIndexRouteImport.update({
  id: '/squads/',
  path: '/squads/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadsSquadIdRoute = SquadsSquadIdRouteImport.update({
  id: '/squads/$squadId',
  path: '/squads/$squadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drone': typeof DroneRoute
  '/gears': typeof GearsRoute
  '/heroes': typeof HeroesRoute
  '/squads/$squadId': typeof SquadsSquadIdRoute
  '/squads/': typeof SquadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drone': typeof DroneRoute
  '/gears': typeof GearsRoute
  '/heroes': typeof HeroesRoute
  '/squads/$squadId': typeof SquadsSquadIdRoute
  '/squads': typeof SquadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drone': typeof DroneRoute
  '/gears': typeof GearsRoute
  '/heroes': typeof HeroesRoute
  '/squads/$squadId': typeof SquadsSquadIdRoute
  '/squads/': typeof SquadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drone'
    | '/gears'
    | '/heroes'
    | '/squads/$squadId'
    | '/squads/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drone' | '/gears' | '/heroes' | '/squads/$squadId' | '/squads'
  id:
    | '__root__'
    | '/'
    | '/drone'
    | '/gears'
    | '/heroes'
    | '/squads/$squadId'
    | '/squads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DroneRoute: typeof DroneRoute
  GearsRoute: typeof GearsRoute
  HeroesRoute: typeof HeroesRoute
  SquadsSquadIdRoute: typeof SquadsSquadIdRoute
  SquadsIndexRoute: typeof SquadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gears': {
      id: '/gears'
      path: '/gears'
      fullPath: '/gears'
      preLoaderRoute: typeof GearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drone': {
      id: '/drone'
      path: '/drone'
      fullPath: '/drone'
      preLoaderRoute: typeof DroneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/': {
      id: '/squads/'
      path: '/squads'
      fullPath: '/squads/'
      preLoaderRoute: typeof SquadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squads/$squadId': {
      id: '/squads/$squadId'
      path: '/squads/$squadId'
      fullPath: '/squads/$squadId'
      preLoaderRoute: typeof SquadsSquadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DroneRoute: DroneRoute,
  GearsRoute: GearsRoute,
  HeroesRoute: HeroesRoute,
  SquadsSquadIdRoute: SquadsSquadIdRoute,
  SquadsIndexRoute: SquadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
