/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as GearsRouteImport } from './routes/gears'
import { Route as IndexRouteImport } from './routes/index'

const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const GearsRoute = GearsRouteImport.update({
  id: '/gears',
  path: '/gears',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gears': typeof GearsRoute
  '/heroes': typeof HeroesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gears': typeof GearsRoute
  '/heroes': typeof HeroesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gears': typeof GearsRoute
  '/heroes': typeof HeroesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gears' | '/heroes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gears' | '/heroes'
  id: '__root__' | '/' | '/gears' | '/heroes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GearsRoute: typeof GearsRoute
  HeroesRoute: typeof HeroesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gears': {
      id: '/gears'
      path: '/gears'
      fullPath: '/gears'
      preLoaderRoute: typeof GearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GearsRoute: GearsRoute,
  HeroesRoute: HeroesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
