package com.lastwar_advisor.server.seeder;

import java.util.List;
import java.util.Set;

import org.springframework.stereotype.Component;

import com.lastwar_advisor.server.entity.StatKey;
import com.lastwar_advisor.server.repository.StatKeyRepository;
import com.lastwar_advisor.server.util.StatKeyConstants;

@Component
public class StatKeySeeder {

        private final StatKeyRepository statKeyRepo;

        public StatKeySeeder(StatKeyRepository statKeyRepo) {
                this.statKeyRepo = statKeyRepo;
        }

        public void seedStatKeys() {

                List<String[]> keys = List.of(
                                // key, description, category, valueType
                                new String[] { StatKeyConstants.ATK_PERCENT, "Attack percentage boost", "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.ENERGY_DAMAGE_PERCENT, "Energy damage boost percentage",
                                                "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.PHYSICAL_DAMAGE_PERCENT,
                                                "Physical damage boost percentage", "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.BONUS_DAMAGE_PERCENT, "Bonus damage percentage",
                                                "Offense", "float" },
                                new String[] { StatKeyConstants.HIT_COUNT, "Number of hits per skill", "Offense",
                                                "int" },
                                new String[] { StatKeyConstants.CRIT_RATE_PERCENT, "Critical hit rate percentage",
                                                "Offense", "float" },
                                new String[] { StatKeyConstants.CRIT_DAMAGE_PERCENT, "Critical hit damage percentage",
                                                "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.TEAM_ATK_BUFF_PERCENT,
                                                "Team-wide attack buff percentage", "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.HERO_ATK_BOOST_PERCENT, "Hero attack boost percentage",
                                                "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.HERO_SKILL_DAMAGE_PERCENT,
                                                "Hero skill damage boost percentage",
                                                "Offense", "float" },
                                new String[] { StatKeyConstants.DEF_PERCENT, "Defense percentage boost", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.HP_PERCENT, "HP percentage boost", "Defense", "float" },
                                new String[] { StatKeyConstants.SHIELD_HP_PERCENT, "Shield value as percentage of HP",
                                                "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.PHYSICAL_DAMAGE_REDUCTION_PERCENT,
                                                "Physical damage reduction percentage", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.ENERGY_DAMAGE_REDUCTION_PERCENT,
                                                "Energy damage reduction percentage",
                                                "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.TEAM_DAMAGE_REDUCTION_PERCENT,
                                                "Team-wide damage reduction percentage",
                                                "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.FRONT_ROW_DAMAGE_REDUCTION_PERCENT,
                                                "Front row damage reduction percentage", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.CRIT_REDUCTION_PERCENT,
                                                "Reduced chance of taking critical hits",
                                                "Defense", "float" },
                                new String[] { StatKeyConstants.HERO_DEF_BOOST_PERCENT, "Hero defense boost percentage",
                                                "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.HERO_HP_BOOST_PERCENT, "Hero HP boost percentage",
                                                "Defense", "float" },
                                new String[] { StatKeyConstants.TEAM_DEF_BUFF_PERCENT,
                                                "Team-wide defense buff percentage", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.COOLDOWN_REDUCTION_PERCENT,
                                                "Skill cooldown reduction percentage",
                                                "Utility",
                                                "float" },
                                new String[] { StatKeyConstants.ATTACK_SPEED_PERCENT, "Attack speed boost percentage",
                                                "Utility",
                                                "float" },
                                new String[] { StatKeyConstants.MOVE_SPEED_PERCENT, "Movement speed boost percentage",
                                                "Utility",
                                                "float" },
                                new String[] { StatKeyConstants.DURATION_S, "Effect duration in seconds", "Utility",
                                                "float" },
                                new String[] { StatKeyConstants.TARGET_UPGRADE,
                                                "Skill target upgrades to full team at higher levels",
                                                "Utility",
                                                "bool" },
                                new String[] { StatKeyConstants.STUN, "Stuns the target", "CrowdControl", "bool" },
                                new String[] { StatKeyConstants.TAUNT, "Forces enemies to target this hero",
                                                "CrowdControl", "bool" },
                                new String[] { StatKeyConstants.ENHANCED_TAUNT,
                                                "Enhanced taunt with additional effects",
                                                "CrowdControl", "bool" },
                                new String[] { StatKeyConstants.TEAM_HEAL_HP_PERCENT, "Team-wide HP heal percentage",
                                                "Support",
                                                "float" },
                                new String[] { StatKeyConstants.BOOST_PHYSICAL_DAMAGE_PERCENT,
                                                "Tech boost to physical damage", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.BOOST_ENERGY_DAMAGE_PERCENT,
                                                "Tech boost to energy damage", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.REDUCE_DAMAGE_TAKEN_PERCENT,
                                                "Tech reduction to damage taken", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.TANK_ATK_BOOST_PERCENT,
                                                "Tank hero attack boost from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.TANK_DEF_BOOST_PERCENT,
                                                "Tank hero defense boost from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.TANK_HP_BOOST_PERCENT, "Tank hero HP boost from tech",
                                                "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.TANK_DAMAGE_BOOST_PERCENT,
                                                "Tank hero damage boost from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.TANK_DAMAGE_REDUCTION_PERCENT,
                                                "Tank hero damage reduction from tech",
                                                "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.AIRCRAFT_ATK_BOOST_PERCENT,
                                                "Aircraft hero attack boost from tech",
                                                "Tech", "float" },
                                new String[] { StatKeyConstants.AIRCRAFT_DEF_BOOST_PERCENT,
                                                "Aircraft hero defense boost from tech",
                                                "Tech", "float" },
                                new String[] { StatKeyConstants.AIRCRAFT_HP_BOOST_PERCENT,
                                                "Aircraft hero HP boost from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.AIRCRAFT_DAMAGE_BOOST_PERCENT,
                                                "Aircraft hero damage boost from tech",
                                                "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.AIRCRAFT_DAMAGE_REDUCTION_PERCENT,
                                                "Aircraft hero damage reduction from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.MISSILE_ATK_BOOST_PERCENT,
                                                "Missile hero attack boost from tech",
                                                "Tech", "float" },
                                new String[] { StatKeyConstants.MISSILE_DEF_BOOST_PERCENT,
                                                "Missile hero defense boost from tech",
                                                "Tech", "float" },
                                new String[] { StatKeyConstants.MISSILE_HP_BOOST_PERCENT,
                                                "Missile hero HP boost from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.MISSILE_DAMAGE_BOOST_PERCENT,
                                                "Missile hero damage boost from tech",
                                                "Tech", "float" },
                                new String[] { StatKeyConstants.MISSILE_DAMAGE_REDUCTION_PERCENT,
                                                "Missile hero damage reduction from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.UNIT_MORALE_BOOST_PERCENT,
                                                "Unit morale boost from tech", "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.UNIT_ATK_BOOST_PERCENT, "Unit attack boost from tech",
                                                "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.UNIT_DEF_BOOST_PERCENT, "Unit defense boost from tech",
                                                "Tech",
                                                "float" },
                                new String[] { StatKeyConstants.UNIT_HP_BOOST_PERCENT, "Unit HP boost from tech",
                                                "Tech", "float" },
                                new String[] { StatKeyConstants.DRONE_LEVEL, "Drone level", "Drone", "int" },
                                new String[] { StatKeyConstants.DRONE_COMBAT_BOOST_LEVEL, "Drone combat boost level",
                                                "Drone", "int" },
                                new String[] { StatKeyConstants.DRONE_CHIP_STARS, "Drone chip star rating", "Drone",
                                                "int" },
                                new String[] { StatKeyConstants.DRONE_HERO_HP_BOOST_PERCENT,
                                                "Drone boost to hero HP percentage",
                                                "Drone", "float" },
                                new String[] { StatKeyConstants.DRONE_HERO_DEF_BOOST_PERCENT,
                                                "Drone boost to hero defense percentage",
                                                "Drone",
                                                "float" },
                                new String[] { StatKeyConstants.DRONE_HERO_ATK_BOOST_PERCENT,
                                                "Drone boost to hero attack percentage",
                                                "Drone",
                                                "float" },
                                new String[] { StatKeyConstants.DRONE_RADAR_LEVEL,
                                                "Drone radar research component level", "Drone",
                                                "int" },
                                new String[] { StatKeyConstants.DRONE_TURBO_LEVEL,
                                                "Drone turbo engine research component level",
                                                "Drone", "int" },
                                new String[] { StatKeyConstants.DRONE_ARMOR_LEVEL,
                                                "Drone external armor research component level",
                                                "Drone", "int" },
                                new String[] { StatKeyConstants.DRONE_THERMAL_LEVEL,
                                                "Drone thermal imager research component level",
                                                "Drone", "int" },
                                new String[] { StatKeyConstants.DRONE_FUEL_LEVEL,
                                                "Drone fuel cell research component level", "Drone",
                                                "int" },
                                new String[] { StatKeyConstants.DRONE_MISSILE_LEVEL,
                                                "Drone airborne missile research component level",
                                                "Drone",
                                                "int" },
                                new String[] { StatKeyConstants.DRONE_HP, "Drone HP integer value", "Drone", "int" },
                                new String[] { StatKeyConstants.DRONE_DEF, "Drone defense integer value", "Drone",
                                                "int" },
                                new String[] { StatKeyConstants.DRONE_ATK, "Drone attack integer value", "Drone",
                                                "int" },
                                new String[] { StatKeyConstants.OVERLORD_ATK, "Overlord attack integer value",
                                                "Overlord", "int" },
                                new String[] { StatKeyConstants.OVERLORD_DEF, "Overlord defense integer value",
                                                "Overlord", "int" },
                                new String[] { StatKeyConstants.OVERLORD_HP, "Overlord HP integer value", "Overlord",
                                                "int" },
                                new String[] { StatKeyConstants.OVERLORD_ATK_BOOST_PERCENT,
                                                "Overlord attack boost percentage",
                                                "Overlord", "float" },
                                new String[] { StatKeyConstants.OVERLORD_DEF_BOOST_PERCENT,
                                                "Overlord defense boost percentage",
                                                "Overlord", "float" },
                                new String[] { StatKeyConstants.OVERLORD_HP_BOOST_PERCENT,
                                                "Overlord HP boost percentage", "Overlord",
                                                "float" },
                                new String[] { StatKeyConstants.OVERLORD_EXPERT_CRIT_RATE_PERCENT,
                                                "Overlord Expert Overlord skill crit rate boost",
                                                "Overlord", "float" },
                                new String[] { StatKeyConstants.HERO_OVERLORD_HP, "Hero and overlord HP integer boost",
                                                "Overlord",
                                                "int" },
                                new String[] { StatKeyConstants.HERO_OVERLORD_DEF,
                                                "Hero and overlord defense integer boost",
                                                "Overlord", "int" },
                                new String[] { StatKeyConstants.HERO_OVERLORD_ATK,
                                                "Hero and overlord attack integer boost", "Overlord",
                                                "int" },
                                new String[] { StatKeyConstants.DECOR_HERO_ATK_BOOST_PERCENT,
                                                "Decoration hero attack boost percentage",
                                                "Decoration",
                                                "float" },
                                new String[] { StatKeyConstants.DECOR_HERO_DEF_BOOST_PERCENT,
                                                "Decoration hero defense boost percentage", "Decoration",
                                                "float" },
                                new String[] { StatKeyConstants.DECOR_HERO_HP_BOOST_PERCENT,
                                                "Decoration hero HP boost percentage",
                                                "Decoration",
                                                "float" },
                                new String[] { StatKeyConstants.DECOR_OVERLORD_ATK_BOOST_PERCENT,
                                                "Decoration overlord attack boost percentage",
                                                "Decoration", "float" },
                                new String[] { StatKeyConstants.DECOR_OVERLORD_DEF_BOOST_PERCENT,
                                                "Decoration overlord defense boost percentage",
                                                "Decoration", "float" },
                                new String[] { StatKeyConstants.DECOR_OVERLORD_HP_BOOST_PERCENT,
                                                "Decoration overlord HP boost percentage",
                                                "Decoration", "float" },
                                new String[] { StatKeyConstants.DECOR_DAMAGE_REDUCTION_PERCENT,
                                                "Decoration damage reduction percentage", "Decoration",
                                                "float" },
                                new String[] { StatKeyConstants.DECOR_CRIT_RATE_PERCENT,
                                                "Decoration crit rate percentage",
                                                "Decoration", "float" },
                                new String[] { StatKeyConstants.COSMETIC_HERO_ATK_BOOST_PERCENT,
                                                "Cosmetic hero attack boost percentage", "Cosmetic",
                                                "float" },
                                new String[] { StatKeyConstants.COSMETIC_HERO_DEF_BOOST_PERCENT,
                                                "Cosmetic hero defense boost percentage", "Cosmetic",
                                                "float" },
                                new String[] { StatKeyConstants.COSMETIC_HERO_HP_BOOST_PERCENT,
                                                "Cosmetic hero HP boost percentage",
                                                "Cosmetic",
                                                "float" },
                                new String[] { StatKeyConstants.COSMETIC_DAMAGE_REDUCTION_PERCENT,
                                                "Cosmetic damage reduction percentage", "Cosmetic",
                                                "float" },
                                new String[] { StatKeyConstants.WOH_AIR_COUNT, "Wall of Honor air hero count",
                                                "WallOfHonor", "int" },
                                new String[] { StatKeyConstants.WOH_AIR_LEVEL, "Wall of Honor air hero total level",
                                                "WallOfHonor",
                                                "int" },
                                new String[] { StatKeyConstants.WOH_TANK_COUNT, "Wall of Honor tank hero count",
                                                "WallOfHonor", "int" },
                                new String[] { StatKeyConstants.WOH_TANK_LEVEL, "Wall of Honor tank hero total level",
                                                "WallOfHonor",
                                                "int" },
                                new String[] { StatKeyConstants.WOH_MISSILE_COUNT, "Wall of Honor missile hero count",
                                                "WallOfHonor",
                                                "int" },
                                new String[] { StatKeyConstants.WOH_MISSILE_LEVEL,
                                                "Wall of Honor missile hero total level",
                                                "WallOfHonor", "int" },
                                new String[] { StatKeyConstants.UNIT_TROOP_LEVEL, "Troop level", "Units", "int" },
                                new String[] { StatKeyConstants.UNIT_QUANTITY, "Quantity of troops per march", "Units",
                                                "int" },
                                new String[] { StatKeyConstants.UNIT_POWER, "Calculated unit power", "Units", "int" },
                                new String[] { StatKeyConstants.TACTICS_CARD_POWER, "Aggregate tactics card power",
                                                "TacticsCards",
                                                "float" },

                                new String[] { StatKeyConstants.HERO_ATK_RAW, "Flat attack power", "Offense",
                                                "int" },
                                new String[] { StatKeyConstants.HERO_DEF_RAW, "Flat defense", "Defense",
                                                "int" },
                                new String[] { StatKeyConstants.HERO_HP_RAW, "Flat HP", "Defense",
                                                "int" },
                                new String[] { StatKeyConstants.RESISTANCE_ALL_DMG_PERCENT,
                                                "Damage reduction percentage that applies to all damage types",
                                                "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.DMG_COUNTER_BOOST_PERCENT,
                                                "Damage counter boost percentage", "Offense",
                                                "float" },
                                new String[] { StatKeyConstants.REDUCE_CRIT_CHANCE_PERCENT,
                                                "Percentage reduction to chance of taking critical hits", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.REDUCE_CRIT_DAMAGE_PERCENT,
                                                "Percentage reduction to critical damage taken", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.PHYSICAL_DAMAGE_RESISTANCE_PERCENT,
                                                "Physical damage resistance percentage", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.ENERGY_DAMAGE_RESISTANCE_PERCENT,
                                                "Energy damage resistance percentage", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.HERO_DAMAGE_REDUCTION_PERCENT,
                                                "Hero damage reduction percentage", "Defense",
                                                "float" },
                                new String[] { StatKeyConstants.ENEMY_UNIT_DEATH_RATE_PERCENT,
                                                "Enemy unit death rate percentage in PvP", "Offense",
                                                "float" }

                );

                Set<String> existingKeys = statKeyRepo.findAll().stream().map(StatKey::getKey)
                                .collect(java.util.stream.Collectors.toSet());

                int seededCount = 0;
                for (String[] k : keys) {
                        if (existingKeys.contains(k[0])) { // Skip if key already exists
                                continue;
                        }
                        seededCount++;
                        System.out.println("Seeding StatKey: " + k[0]);
                        StatKey sk = new StatKey();
                        sk.setKey(k[0]);
                        sk.setDescription(k[1]);
                        sk.setCategory(k[2]);
                        sk.setValueType(k[3]);
                        statKeyRepo.save(sk);
                }
                if (seededCount > 0) {
                        System.out.println("Seeded " + seededCount + " StatKeys.");
                } else {
                        System.out.println("StatKeys already seeded, skipping.");
                }

        }

}
