spring.datasource.url=jdbc:postgresql://localhost:5433/lastwar
spring.datasource.username=lastwar
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect